#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

setopt AUTO_CD
setopt MULTIOS
setopt AUTO_PUSHD
setopt AUTO_NAME_DIRS
setopt GLOB_COMPLETE
setopt PUSHD_MINUS
setopt PUSHD_TO_HOME
setopt PUSHD_IGNORE_DUPS
setopt RM_STAR_WAIT
setopt ZLE
setopt NO_HUP
setopt IGNORE_EOF
setopt NO_FLOW_CONTROL
setopt NO_CLOBBER
setopt NO_CASE_GLOB
setopt EXTENDED_GLOB
setopt RC_EXPAND_PARAM

# Local Cabal path
export PATH=$PATH:/home/pablo/.cabal/bin


# Who doesn't want home and end to work?
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

bindkey "\eOP" run-help
bindkey -M vicmd "q" push-line
bindkey -M viins ' ' magic-space

# no underline in syntax highlighting

ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none
ZSH_HIGHLIGHT_STYLES[path_approx]=fg=yellow

# plain cursor
ZSH_HIGHLIGHT_STYLES[cursor]=none

# Aliases

alias y='pacman'
alias ut='tar xvf'
alias utz='tar xvfz'
open () { command xdg-open $* & }
alias o=open
alias -g cth-remote=buiras@remote12.chalmers.se
alias -g the-printer=cse-ed-5473-laser1
wifi-connect () { command wicd-cli --wireless -n $* -c }